# Capstone Project - 01 - Data Import & Cleaning

### Data Sources 

1. [Economic Research Service (ERS), U.S. Department of Agriculture (USDA). Food Environment Atlas (2020).](https://www.ers.usda.gov/data-products/food-environment-atlas/data-access-and-documentation-downloads/)

2. [Center for Disease Control (CDC). Diagnosed Diabetes- National, Natural Breaks, 2018; Social Vulnerability Index (SVI), Overall SVI.](https://gis.cdc.gov/grasp/diabetes/diabetesatlas-sdoh.html#)

3. [American Health Rankings - United Health Foundation. National Health Providers (2017).](https://www.americashealthrankings.org/explore/annual/measure/MHP?edition-year=2017)

4. [American Health Rankings - United Health Foundation. National Health Providers (2018).](https://www.americashealthrankings.org/explore/annual/measure/MHP?edition-year=2018)

5. [NSDUH State Estimates – Individual Excel and CSV Files by Outcome (2015-2016).](https://www.samhsa.gov/data/report/2015-2016-nsduh-state-estimates-individual-excel-and-csv-files-outcome)

## Introduction



In this notebook, I create dataframes of the data and conduct preliminary analysis in order to observe for issues. Additionally, I begin cleaning the data by removing certain unneeded columns and revising column names, and then observe for issues that will need to be corrected after further analysis.

*I recommend opening the Variable List as part of the Food Environment Atlas spreadsheet while reading through these notebooks in order to understand the variable names as listed below.*

## I. Food Environmental Atlas - Variable List

This is essentially a Data Dictionary containing the many variables present within the Food Environmental Atlas.

I will observe for any issues.

### 1. Data Import

In [1]:
import pandas as pd
import numpy as np

In [2]:
#importing the data

file_path = '../data/FoodEnvironmentAtlas.xls.VariableList.csv'

variables = pd.read_csv(file_path)

### 2. Preliminary Observations

In [3]:
variables.shape #shows the layout of the dataframe

(281, 7)

In [4]:
variables.isnull().sum() #shows the number of missing values per column

Category Name       0
Category Code       0
Subcategory Name    0
Variable Name       0
Variable Code       0
Geography           0
Units               0
dtype: int64

As anticipated, no values are missing. However, the spaces in the column names might present an issue. Meanwhile, pressing "shift" for upper case letters in undesirable. The column names will be edited.

In [5]:
variables.columns = [col.lower() for col in variables.columns] #makes all letters in column names lowercase

variables.columns = variables.columns.str.replace(" " , "_") #replaces spaces in column names with underscore

variables.columns

Index(['category_name', 'category_code', 'subcategory_name', 'variable_name',
       'variable_code', 'geography', 'units'],
      dtype='object')

In [6]:
variables.dtypes #shows datatypes of the columns

category_name       object
category_code       object
subcategory_name    object
variable_name       object
variable_code       object
geography           object
units               object
dtype: object

The issues have been resolved. I do not anticipate that any other issues would be present. The cleaned dataframe will be saved as a csv, then uploaded into the diabetes database for storage.

#### 3. Saving Clean File to a csv

In [7]:
variables.to_csv('../data/FoodEnvironmentAtlas.xls.VariableList_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## II. Food Environmental Atlas - HEALTH

This dataset contains information regarding physical health, such as prevalence of diabetes in 2008 and 2013, prevalence of obesity, recreational facilities, and percentage of high schoolers that are physically active. 

I will import the data, and observe for any issues.

### 1. Data Import

In [8]:
#importing the data

file_path = '../data/FoodEnvironmentAtlas.xls.HEALTH.csv'

health = pd.read_csv(file_path)

### 2. Preliminary Observations

In [9]:
health.head() #displays the top 5 rows of the dataframe

FIPS State   County  PCT_DIABETES_ADULTS08  PCT_DIABETES_ADULTS13  \
0  1001    AL  Autauga                   11.4                   13.0   
1  1003    AL  Baldwin                    9.8                   10.4   
2  1005    AL  Barbour                   13.6                   18.4   
3  1007    AL     Bibb                   11.1                   14.8   
4  1009    AL   Blount                   11.4                   14.1   

   PCT_OBESE_ADULTS12  PCT_OBESE_ADULTS17  PCT_HSPA17  RECFAC11  RECFAC16  \
0                33.0                36.3         NaN         4         6   
1                33.0                36.3         NaN        16        21   
2                33.0                36.3         NaN         2         0   
3                33.0                36.3         NaN         0         1   
4                33.0                36.3         NaN         3         4   

   PCH_RECFAC_11_16  RECFACPTH11  RECFACPTH16  PCH_RECFACPTH_11_16  
0         50.000000     0.072465     0.108542            49.785629  
1         31.250000     0.085775     0.101200            17.983256  
2       -100.000000     0.073123     0.000000          -100.000000  
3               NaN     0.000000     0.044183                  NaN  
4         33.333333     0.052118     0.069490            33.333333

In [10]:
health.shape #displays the layout of the dataframe

(3143, 14)

In [11]:
health.columns #displays column names

Index(['FIPS', 'State', 'County', 'PCT_DIABETES_ADULTS08',
       'PCT_DIABETES_ADULTS13', 'PCT_OBESE_ADULTS12', 'PCT_OBESE_ADULTS17',
       'PCT_HSPA17', 'RECFAC11', 'RECFAC16', 'PCH_RECFAC_11_16', 'RECFACPTH11',
       'RECFACPTH16', 'PCH_RECFACPTH_11_16'],
      dtype='object')

These capital letters will become bothersome. I wil change them to all lowercase.

In [12]:
health.columns = [col.lower() for col in health.columns]

health.columns

Index(['fips', 'state', 'county', 'pct_diabetes_adults08',
       'pct_diabetes_adults13', 'pct_obese_adults12', 'pct_obese_adults17',
       'pct_hspa17', 'recfac11', 'recfac16', 'pch_recfac_11_16', 'recfacpth11',
       'recfacpth16', 'pch_recfacpth_11_16'],
      dtype='object')

In [13]:
health.isnull().sum() #shows the number of missing values per column

fips                       0
state                      0
county                     0
pct_diabetes_adults08      5
pct_diabetes_adults13      1
pct_obese_adults12         0
pct_obese_adults17         0
pct_hspa17               760
recfac11                   0
recfac16                   0
pch_recfac_11_16         143
recfacpth11                0
recfacpth16                0
pch_recfacpth_11_16      143
dtype: int64

I see that there are missing values. I will determine what to do about this after viewing more information during EDA.

In [14]:
health.dtypes #shows the datatype for each row

fips                       int64
state                     object
county                    object
pct_diabetes_adults08    float64
pct_diabetes_adults13    float64
pct_obese_adults12       float64
pct_obese_adults17       float64
pct_hspa17               float64
recfac11                   int64
recfac16                   int64
pch_recfac_11_16         float64
recfacpth11              float64
recfacpth16              float64
pch_recfacpth_11_16      float64
dtype: object

These are the appropriate data types.

### 3. Data Cleaning by Column

It appears that this information is reviewed, and seems unlikely to contain errors. Still, I will observe statistics for each column.

In [15]:
health.pct_diabetes_adults08.describe() #displays a statistical summary of this column

count    3138.000000
mean        9.913257
std         2.058922
min         3.000000
25%         8.500000
50%         9.800000
75%        11.300000
max        18.200000
Name: pct_diabetes_adults08, dtype: float64

No issues observed.

In [16]:
health.pct_diabetes_adults13.describe() #displays a statistical summary of this column

count    3142.000000
mean       11.236123
std         2.485537
min         3.300000
25%         9.500000
50%        11.100000
75%        12.900000
max        23.500000
Name: pct_diabetes_adults13, dtype: float64

No issues observed.

In [17]:
health.pct_obese_adults12.describe() #displays a statistical summary of this column

count    3143.000000
mean       29.056570
std         2.979568
min        20.500000
25%        27.400000
50%        29.200000
75%        31.100000
max        34.700000
Name: pct_obese_adults12, dtype: float64

In [18]:
health.pct_obese_adults17.describe() #displays a statistical summary of this column

count    3143.000000
mean       31.862965
std         3.329267
min        22.600000
25%        30.100000
50%        32.400000
75%        33.800000
max        38.100000
Name: pct_obese_adults17, dtype: float64

In [19]:
health.pct_hspa17.describe() #displays a statistical summary of this column

count    2383.000000
mean       24.620520
std         2.822971
min        13.400000
25%        22.400000
50%        24.700000
75%        26.500000
max        30.800000
Name: pct_hspa17, dtype: float64

In [20]:
health.recfac11.describe() #displays a statistical summary of the column

count    3143.000000
mean        9.382755
std        29.677411
min         0.000000
25%         0.000000
50%         2.000000
75%         6.000000
max       714.000000
Name: recfac11, dtype: float64

In [21]:
health.recfac16.describe() #displays a statistical summary of the column

count    3143.000000
mean       10.807509
std        36.985652
min         0.000000
25%         0.000000
50%         2.000000
75%         6.000000
max       939.000000
Name: recfac16, dtype: float64

In [22]:
health.pch_recfac_11_16.describe() #displays a statistical summary of the column

count    3000.000000
mean        1.030283
std        50.972792
min      -100.000000
25%       -10.051020
50%         0.000000
75%         9.942748
max       600.000000
Name: pch_recfac_11_16, dtype: float64

Negative values here could be appropriate, as this value refers to a percent change. Seeing a percent change of -100% is surprising, but certainly not impossible.

No issues observed.

In [23]:
health.recfacpth11.describe() #displays a statisical summary of the column

count    3143.000000
mean        0.071337
std         0.073805
min         0.000000
25%         0.000000
50%         0.064726
75%         0.107117
max         0.628141
Name: recfacpth11, dtype: float64

In [24]:
health.recfacpth11.describe() #displays a statisical summary of the column

count    3143.000000
mean        0.071337
std         0.073805
min         0.000000
25%         0.000000
50%         0.064726
75%         0.107117
max         0.628141
Name: recfacpth11, dtype: float64

In [25]:
health.recfacpth16.describe() #displays a statistical summary of the column

count    3143.000000
mean        0.070300
std         0.075829
min         0.000000
25%         0.000000
50%         0.061983
75%         0.108090
max         1.053741
Name: recfacpth16, dtype: float64

In [26]:
health.pch_recfacpth_11_16.describe() #displays a statistical summary of the column

count    3000.000000
mean       -0.095421
std        50.007496
min      -100.000000
25%       -12.143966
50%         0.000000
75%         6.399759
max       626.403236
Name: pch_recfacpth_11_16, dtype: float64

Again, negative percent changes are entirely possible.

No issues observed.

#### Discussion

I had hoped to use the data regarding physically active high schoolers (2017), however, there are too many missing values (760 out of 3143.) I will still analyze whatever information is present, however I will not use this variable for modeling.

The percent change columns are also missing data (143 each), but these can be calculated if necessary. 

The prevalence of diabetes columns from 2008 and 2013 are missing 5 values and 1 value respectively. These variables, of course, will not be used for modeling. There is sufficient information within the 2 columns to gain understanding of how the other variables within the Food Environment Atlas affect prevalence of diabetes in general.

Therefore, no additional changes will be made to the Health dataset at ths time.

### 4. Saving Clean Dataframe to a CSV

In [27]:
health.to_csv('../data/FoodEnvironmentAtlas.xls.HEALTH_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## III. Food Environmental Atlas - ACCESS 

This dataset contains information about access to stores, including percentages of the population that has low access to stores, along with being low income, who do not have a vehicle, and so on.

### 1. Data Import

In [28]:
#importing the data

file_path = '../data/FoodEnvironmentAtlas.xls.ACCESS.csv'

access = pd.read_csv(file_path)

### 2. Preliminary Analysis

In [29]:
access.head() #displays top 5 rows of dataframe

FIPS State   County  LACCESS_POP10  LACCESS_POP15  PCH_LACCESS_POP_10_15  \
0  1001    AL  Autauga   18428.439690   17496.693040              -5.056026   
1  1003    AL  Baldwin   35210.814080   30561.264430             -13.204891   
2  1005    AL  Barbour    5722.305602    6069.523628               6.067799   
3  1007    AL     Bibb    1044.867327     969.378841              -7.224696   
4  1009    AL   Blount    1548.175559    3724.428242             140.568857   

   PCT_LACCESS_POP10  PCT_LACCESS_POP15  LACCESS_LOWI10  LACCESS_LOWI15  ...  \
0          33.769657          32.062255     5344.427472     6543.676824  ...   
1          19.318473          16.767489     9952.144027     9886.831137  ...   
2          20.840972          22.105560     3135.676086     2948.790251  ...   
3           4.559753           4.230324      491.449066      596.162829  ...   
4           2.700840           6.497380      609.027708     1650.959482  ...   

   LACCESS_HISP15  PCT_LACCESS_HISP15  LACCESS_NHASIAN15  \
0      471.136164            0.863345          86.767975   
1     1377.874834            0.755973         212.946378   
2      509.377525            1.855183          17.096410   
3        8.596762            0.037516           1.994318   
4      497.489891            0.867886           8.428994   

   PCT_LACCESS_NHASIAN15  LACCESS_NHNA15  PCT_LACCESS_NHNA15  LACCESS_NHPI15  \
0               0.159000       61.169869            0.112092        8.817961   
1               0.116833      181.649648            0.099662       14.819634   
2               0.062266       39.960527            0.145539        8.082376   
3               0.008703        2.513097            0.010967        0.000000   
4               0.014705       28.938242            0.050484        1.062851   

   PCT_LACCESS_NHPI15  LACCESS_MULTIR15  PCT_LACCESS_MULTIR15  
0            0.016159        482.848633              0.884808  
1            0.008131       1127.696098              0.618712  
2            0.029436        462.382655              1.684025  
3            0.000000          5.259244              0.022951  
4            0.001854        202.914186              0.353990  

[5 rows x 44 columns]

In [30]:
access.shape #shows layout of dataframe

(3143, 44)

In [31]:
access.isnull().sum() #shows number of null values for each column

FIPS                          0
State                         0
County                        0
LACCESS_POP10                 0
LACCESS_POP15                19
PCH_LACCESS_POP_10_15        26
PCT_LACCESS_POP10             0
PCT_LACCESS_POP15            19
LACCESS_LOWI10                0
LACCESS_LOWI15               20
PCH_LACCESS_LOWI_10_15       28
PCT_LACCESS_LOWI10            0
PCT_LACCESS_LOWI15           20
LACCESS_HHNV10                0
LACCESS_HHNV15                3
PCH_LACCESS_HHNV_10_15       14
PCT_LACCESS_HHNV10            0
PCT_LACCESS_HHNV15            3
LACCESS_SNAP15               20
PCT_LACCESS_SNAP15           20
LACCESS_CHILD10               0
LACCESS_CHILD15              19
LACCESS_CHILD_10_15          28
PCT_LACCESS_CHILD10           0
PCT_LACCESS_CHILD15          19
LACCESS_SENIORS10             0
LACCESS_SENIORS15            19
PCH_LACCESS_SENIORS_10_15    26
PCT_LACCESS_SENIORS10         0
PCT_LACCESS_SENIORS15        19
LACCESS_WHITE15              19
PCT_LACC

At this time, no null values will be filled. If they need to be filled at a later time in order to faciliate analysis, that will be decided at the time.

In [32]:
access.columns #shows names of all columns

Index(['FIPS', 'State', 'County', 'LACCESS_POP10', 'LACCESS_POP15',
       'PCH_LACCESS_POP_10_15', 'PCT_LACCESS_POP10', 'PCT_LACCESS_POP15',
       'LACCESS_LOWI10', 'LACCESS_LOWI15', 'PCH_LACCESS_LOWI_10_15',
       'PCT_LACCESS_LOWI10', 'PCT_LACCESS_LOWI15', 'LACCESS_HHNV10',
       'LACCESS_HHNV15', 'PCH_LACCESS_HHNV_10_15', 'PCT_LACCESS_HHNV10',
       'PCT_LACCESS_HHNV15', 'LACCESS_SNAP15', 'PCT_LACCESS_SNAP15',
       'LACCESS_CHILD10', 'LACCESS_CHILD15', 'LACCESS_CHILD_10_15',
       'PCT_LACCESS_CHILD10', 'PCT_LACCESS_CHILD15', 'LACCESS_SENIORS10',
       'LACCESS_SENIORS15', 'PCH_LACCESS_SENIORS_10_15',
       'PCT_LACCESS_SENIORS10', 'PCT_LACCESS_SENIORS15', 'LACCESS_WHITE15',
       'PCT_LACCESS_WHITE15', 'LACCESS_BLACK15', 'PCT_LACCESS_BLACK15',
       'LACCESS_HISP15', 'PCT_LACCESS_HISP15', 'LACCESS_NHASIAN15',
       'PCT_LACCESS_NHASIAN15', 'LACCESS_NHNA15', 'PCT_LACCESS_NHNA15',
       'LACCESS_NHPI15', 'PCT_LACCESS_NHPI15', 'LACCESS_MULTIR15',
       'PCT_LACCESS_MULT

There are many columns here! I am not certain that all of these are needed...

For example, I am uncertain that I would like to use ethnicity to predict prevalence of diabetes. My intention in the current study is to demonstrate how aspects of food environment can affect prevalence of diabetes, not how "certain" ethnic groups are more or less prone to disease.

(I.e. if populations with certain ethnic groups had higher prevalence of diabetes, I would not like for anyone to conclude that it is because there are "too many of THOSE people" living there.)

For now, I will not include the columns related to ethnicity in additional analysis. Additionally, I will include percentages instead of raw numbers so as to be able to generalize to counties of any population size.



In [33]:
#redefines dataset as described above

access = access[['FIPS', 'State', 'County', 'PCT_LACCESS_POP10', 'PCT_LACCESS_POP15', 'PCT_LACCESS_LOWI10', 'PCT_LACCESS_LOWI15', 'PCT_LACCESS_HHNV10', 'PCT_LACCESS_HHNV15', 'PCT_LACCESS_SNAP15', 'PCT_LACCESS_CHILD10', 'PCT_LACCESS_CHILD15', 'PCT_LACCESS_SENIORS10' , 'PCT_LACCESS_SENIORS15']]

access.columns #displays revised list of columns
          

Index(['FIPS', 'State', 'County', 'PCT_LACCESS_POP10', 'PCT_LACCESS_POP15',
       'PCT_LACCESS_LOWI10', 'PCT_LACCESS_LOWI15', 'PCT_LACCESS_HHNV10',
       'PCT_LACCESS_HHNV15', 'PCT_LACCESS_SNAP15', 'PCT_LACCESS_CHILD10',
       'PCT_LACCESS_CHILD15', 'PCT_LACCESS_SENIORS10',
       'PCT_LACCESS_SENIORS15'],
      dtype='object')

This list of columns is much less intimidating! I included the percentages and not the raw numbers or percent changes. I excluded the columns with data about ethnicity.

Next, I would like to make the columns lowercase for ease of use.

In [34]:
access.columns = [col.lower() for col in access.columns] #makes letters in column names lowercase

access.columns #displays revised column names

Index(['fips', 'state', 'county', 'pct_laccess_pop10', 'pct_laccess_pop15',
       'pct_laccess_lowi10', 'pct_laccess_lowi15', 'pct_laccess_hhnv10',
       'pct_laccess_hhnv15', 'pct_laccess_snap15', 'pct_laccess_child10',
       'pct_laccess_child15', 'pct_laccess_seniors10',
       'pct_laccess_seniors15'],
      dtype='object')

In [35]:
access.dtypes #displays the datatypes of the columns

fips                       int64
state                     object
county                    object
pct_laccess_pop10        float64
pct_laccess_pop15        float64
pct_laccess_lowi10       float64
pct_laccess_lowi15       float64
pct_laccess_hhnv10       float64
pct_laccess_hhnv15       float64
pct_laccess_snap15       float64
pct_laccess_child10      float64
pct_laccess_child15      float64
pct_laccess_seniors10    float64
pct_laccess_seniors15    float64
dtype: object

#### 3. Data Cleaning By Column

##### Pct low access pop 10

In [36]:
access.pct_laccess_pop10.nunique() #shows number of unique values for this column

3091

In [37]:
access.pct_laccess_pop10.value_counts() #shows value counts

0.000000      28
100.000000     8
100.000000     6
100.000000     4
100.000000     3
              ..
16.642450      1
0.189767       1
17.752938      1
8.928767       1
17.209949      1
Name: pct_laccess_pop10, Length: 3091, dtype: int64

It appears there are 28 counties in which the low access is 0.

This dataframe is sufficiently clean for the moment. If the blank values must be filled, I will do this at a later time.

### 3. Saving Clean Dataframe to a CSV

In [38]:
access.to_csv('../data/FoodEnvironmentAtlas.xls.ACCESS_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## III. Food Environmental Atlas - ASSISTANCE

This dataset contains information regarding recipients of public benefits related to food including SNAP (Supplemental Nutrition Assistance Program,) WIC, and also the number of Food Banks within a county.

### 1. Data Import

In [39]:
file_path = '../data/FoodEnvironmentAtlas.xls.ASSISTANCE.csv'

assistance = pd.read_csv(file_path)

### 2. Preliminary Analysis

In [40]:
assistance.head() #shows top 5 rows of dataframe

FIPS State   County  REDEMP_SNAPS12  REDEMP_SNAPS17  \
0  1001    AL  Autauga     301432.0811     223185.6784   
1  1003    AL  Baldwin     274394.5037     157623.1336   
2  1005    AL  Barbour     325496.5608     257032.0789   
3  1007    AL     Bibb     356444.0320     227725.2451   
4  1009    AL   Blount     229730.0226     142860.8256   

   PCH_REDEMP_SNAPS_12_17  PCT_SNAP12  PCT_SNAP17  PCH_SNAP_12_17  \
0              -25.958220   18.908476   16.500056        -2.40842   
1              -42.556016   18.908476   16.500056        -2.40842   
2              -21.033857   18.908476   16.500056        -2.40842   
3              -36.111921   18.908476   16.500056        -2.40842   
4              -37.813602   18.908476   16.500056        -2.40842   

   PC_SNAPBEN12  ...  PCT_WICWOMEN14  PCT_WICWOMEN16  PCH_WICWOMEN_14_16  \
0     18.471487  ...        3.318827        3.309759           -0.009068   
1     15.890722  ...        3.318827        3.309759           -0.009068   
2     31.116222  ...        3.318827        3.309759           -0.009068   
3     22.435049  ...        3.318827        3.309759           -0.009068   
4     20.272305  ...        3.318827        3.309759           -0.009068   

   PCT_CACFP12  PCT_CACFP17  PCH_CACFP_12_17  FDPIR12  FDPIR15  \
0     0.891239     1.258763         0.367524        0        0   
1     0.891239     1.258763         0.367524        0        0   
2     0.891239     1.258763         0.367524        0        0   
3     0.891239     1.258763         0.367524        0        0   
4     0.891239     1.258763         0.367524        0        0   

   PCH_FDPIR_12_15  FOOD_BANKS18  
0              0.0             0  
1              0.0             0  
2              0.0             0  
3              0.0             0  
4              0.0             0  

[5 rows x 57 columns]

In [41]:
assistance.shape #shows layout of dataframe

(3143, 57)

There are 57 columns in this dataset!

I will need to use a model that does well with high-dimension datasets.

In [42]:
assistance.dtypes #displays datatypes for the columns

FIPS                          int64
State                        object
County                       object
REDEMP_SNAPS12              float64
REDEMP_SNAPS17              float64
PCH_REDEMP_SNAPS_12_17      float64
PCT_SNAP12                  float64
PCT_SNAP17                  float64
PCH_SNAP_12_17              float64
PC_SNAPBEN12                float64
PC_SNAPBEN17                float64
PCH_PC_SNAPBEN_12_17        float64
SNAP_PART_RATE11            float64
SNAP_PART_RATE16            float64
SNAP_OAPP09                 float64
SNAP_OAPP16                 float64
SNAP_CAP09                    int64
SNAP_CAP16                    int64
SNAP_BBCE09                   int64
SNAP_BBCE16                   int64
SNAP_REPORTSIMPLE09           int64
SNAP_REPORTSIMPLE16           int64
PCT_NSLP12                  float64
PCT_NSLP17                  float64
PCH_NSLP_12_17              float64
PCT_FREE_LUNCH10            float64
PCT_FREE_LUNCH15            float64
PCT_REDUCED_LUNCH10         

In [43]:
assistance.isnull().sum() #displays number of missing values

FIPS                           0
State                          0
County                         0
REDEMP_SNAPS12               242
REDEMP_SNAPS17               248
PCH_REDEMP_SNAPS_12_17       299
PCT_SNAP12                     0
PCT_SNAP17                     0
PCH_SNAP_12_17                 0
PC_SNAPBEN12                  56
PC_SNAPBEN17                  56
PCH_PC_SNAPBEN_12_17          56
SNAP_PART_RATE11               0
SNAP_PART_RATE16               0
SNAP_OAPP09                    0
SNAP_OAPP16                    0
SNAP_CAP09                     0
SNAP_CAP16                     0
SNAP_BBCE09                    0
SNAP_BBCE16                    0
SNAP_REPORTSIMPLE09            0
SNAP_REPORTSIMPLE16            0
PCT_NSLP12                     0
PCT_NSLP17                     0
PCH_NSLP_12_17                 0
PCT_FREE_LUNCH10              21
PCT_FREE_LUNCH15             289
PCT_REDUCED_LUNCH10           31
PCT_REDUCED_LUNCH15          289
PCT_SBP12                      0
PCT_SBP17 

Some of the columns are missing values. Additionally, this is a great deal of information...

Meanwhile, according to [this reference](https://www.dshs.wa.gov/sites/default/files/ESA/csd/documents/Basic%20Food_Q_and_A.pdf), eligibility for SNAP, WIC, and free meals at schools seem to be related.

For now, I will focus on columns that contain fewest missing values, while retaining as much information as possible. I will retain the following columns:

FIPS

State

County

pct_snap_12

pct_snap_17

snap_part_rate11

snap_part_rate16

pct_nslp12

pct_nslp17

pct_sbp12

pct_sbp17

pct_wic12

pct_wic17

pct_wicinfantchild14

pct_wicinfantchild16

pct_wicwomen14

pct_wicwomen16

pct_cacfp12

pct_cacfp17

fdpir12

fdpir15

food_banks18

In [44]:
assistance.columns = [col.lower() for col in assistance.columns] #changes column names to lowercase

assistance.columns

Index(['fips', 'state', 'county', 'redemp_snaps12', 'redemp_snaps17',
       'pch_redemp_snaps_12_17', 'pct_snap12', 'pct_snap17', 'pch_snap_12_17',
       'pc_snapben12', 'pc_snapben17', 'pch_pc_snapben_12_17',
       'snap_part_rate11', 'snap_part_rate16', 'snap_oapp09', 'snap_oapp16',
       'snap_cap09', 'snap_cap16', 'snap_bbce09', 'snap_bbce16',
       'snap_reportsimple09', 'snap_reportsimple16', 'pct_nslp12',
       'pct_nslp17', 'pch_nslp_12_17', 'pct_free_lunch10', 'pct_free_lunch15',
       'pct_reduced_lunch10', 'pct_reduced_lunch15', 'pct_sbp12', 'pct_sbp17',
       'pch_sbp_12_17', 'pct_sfsp12', 'pct_sfsp17', 'pch_sfsp_12_17',
       'pc_wic_redemp11', 'pc_wic_redemp16', 'pch_pc_wic_redemp_11_16',
       'redemp_wics11', 'redemp_wics16', 'pch_redemp_wics_11_16', 'pct_wic12',
       'pct_wic17', 'pch_wic_12_17', 'pct_wicinfantchild14',
       'pct_wicinfantchild16', 'pch_wicinfantchild_14_16', 'pct_wicwomen14',
       'pct_wicwomen16', 'pch_wicwomen_14_16', 'pct_cacfp12', 

Now, I will trim the dataset to include only those I listed above. This will facilitate some of the analysis I plan to conduct in SQL. However, I may return to using the full dataset at a later time.

In [45]:
#redefines dataframe to include only referenced columns

assistance = (assistance[['fips', 'state','county', 'pct_snap12', 'pct_snap17', 'snap_part_rate11', 'snap_part_rate16' , 'pct_nslp12',
                         'pct_nslp17', 'pct_sbp12', 'pct_sbp17', 'pct_wic12' , 'pct_wic17', 'pct_wicinfantchild14', 'pct_wicinfantchild16', 
                          'pct_wicwomen14' , 'pct_wicwomen16' , 'pct_cacfp12', 'pct_cacfp17', 'fdpir12', 'fdpir15', 'food_banks18' ]])

assistance.head() #shows the top 5 rows of the revised dataframe

fips state   county  pct_snap12  pct_snap17  snap_part_rate11  \
0  1001    AL  Autauga   18.908476   16.500056             84.02   
1  1003    AL  Baldwin   18.908476   16.500056             84.02   
2  1005    AL  Barbour   18.908476   16.500056             84.02   
3  1007    AL     Bibb   18.908476   16.500056             84.02   
4  1009    AL   Blount   18.908476   16.500056             84.02   

   snap_part_rate16  pct_nslp12  pct_nslp17  pct_sbp12  ...  pct_wic17  \
0            86.898   68.226043    63.12659  27.206328  ...    2.54357   
1            86.898   68.226043    63.12659  27.206328  ...    2.54357   
2            86.898   68.226043    63.12659  27.206328  ...    2.54357   
3            86.898   68.226043    63.12659  27.206328  ...    2.54357   
4            86.898   68.226043    63.12659  27.206328  ...    2.54357   

   pct_wicinfantchild14  pct_wicinfantchild16  pct_wicwomen14  pct_wicwomen16  \
0             33.481211             32.910876        3.318827        3.309759   
1             33.481211             32.910876        3.318827        3.309759   
2             33.481211             32.910876        3.318827        3.309759   
3             33.481211             32.910876        3.318827        3.309759   
4             33.481211             32.910876        3.318827        3.309759   

   pct_cacfp12  pct_cacfp17  fdpir12  fdpir15  food_banks18  
0     0.891239     1.258763        0        0             0  
1     0.891239     1.258763        0        0             0  
2     0.891239     1.258763        0        0             0  
3     0.891239     1.258763        0        0             0  
4     0.891239     1.258763        0        0             0  

[5 rows x 22 columns]

In [46]:
assistance.shape #shows the layout of the revised dataframe

(3143, 22)

In [47]:
assistance.dtypes #displays the datatypes of the remaining columns

fips                      int64
state                    object
county                   object
pct_snap12              float64
pct_snap17              float64
snap_part_rate11        float64
snap_part_rate16        float64
pct_nslp12              float64
pct_nslp17              float64
pct_sbp12               float64
pct_sbp17               float64
pct_wic12               float64
pct_wic17               float64
pct_wicinfantchild14    float64
pct_wicinfantchild16    float64
pct_wicwomen14          float64
pct_wicwomen16          float64
pct_cacfp12             float64
pct_cacfp17             float64
fdpir12                   int64
fdpir15                   int64
food_banks18              int64
dtype: object

It appears the change was successful. I will save this revised dataframe as a csv, and enter it into the database.

### 3. Saving clean dataframe as a csv

In [48]:
assistance.to_csv('../data/FoodEnvironmentAtlas.xls.ASSISTANCE_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## IV. Food Environment Atlas - INSECURITY

This dataset contains information regarding food insecurity in counties, namely prevalence of "food insecurity" and "very low food security."

I will observe for issues.

### 1. Data Import

In [49]:
file_path = '../data/FoodEnvironmentAtlas.xls.INSECURITY.csv'

insecurity = pd.read_csv(file_path)

### 2. Preliminary Analysis & Cleaning

In [50]:
insecurity.head() #shows top 5 rows of dataframe

FIPS State   County  FOODINSEC_12_14  FOODINSEC_15_17  CH_FOODINSEC_14_17  \
0  1001    AL  Autauga             16.8             16.3                -0.5   
1  1003    AL  Baldwin             16.8             16.3                -0.5   
2  1005    AL  Barbour             16.8             16.3                -0.5   
3  1007    AL     Bibb             16.8             16.3                -0.5   
4  1009    AL   Blount             16.8             16.3                -0.5   

   VLFOODSEC_12_14  VLFOODSEC_15_17  CH_VLFOODSEC_14_17  
0              7.2              7.1                -0.1  
1              7.2              7.1                -0.1  
2              7.2              7.1                -0.1  
3              7.2              7.1                -0.1  
4              7.2              7.1                -0.1

In [51]:
insecurity.shape #shows layout of dataframe

(3143, 9)

Nine columns are less cumbersome to work with. Furthermore, I am interested to see how food security might be used to predict prevalence of diabetes.

In [52]:
insecurity.columns = [col.lower() for col in insecurity.columns] #changes column names to lowercase

insecurity.columns #shows column names

Index(['fips', 'state', 'county', 'foodinsec_12_14', 'foodinsec_15_17',
       'ch_foodinsec_14_17', 'vlfoodsec_12_14', 'vlfoodsec_15_17',
       'ch_vlfoodsec_14_17'],
      dtype='object')

In [53]:
insecurity.isnull().sum() #displays number of missing values per column

fips                  0
state                 0
county                0
foodinsec_12_14       0
foodinsec_15_17       0
ch_foodinsec_14_17    0
vlfoodsec_12_14       0
vlfoodsec_15_17       0
ch_vlfoodsec_14_17    0
dtype: int64

There are no missing values! However, the README of the Food Environment Atlas contains a statement indicating that blank values may be filled with -9999. It is possible this might exist here (or in any of the numerical columns...)

I will observe summary statistics in order to see maximum and minimum values.

##### Summary Statistics 

In [54]:
insecurity.foodinsec_12_14.describe()

count    3143.000000
mean       14.863952
std         2.599730
min         8.400000
25%        12.600000
50%        15.200000
75%        16.800000
max        22.000000
Name: foodinsec_12_14, dtype: float64

In [55]:
insecurity.foodinsec_15_17.describe()

count    3143.000000
mean       12.833726
std         2.194020
min         7.400000
25%        11.200000
50%        13.000000
75%        14.000000
max        17.900000
Name: foodinsec_15_17, dtype: float64

In [56]:
insecurity.ch_foodinsec_14_17.describe()

count    3143.000000
mean       -2.030226
std         1.699917
min        -4.900000
25%        -3.200000
50%        -2.600000
75%        -0.900000
max         5.600000
Name: ch_foodinsec_14_17, dtype: float64

Negative values are acceptable here, as this column represents a change in percentage.

In [57]:
insecurity.vlfoodsec_12_14.describe()

count    3143.000000
mean        5.915527
std         0.980072
min         2.900000
25%         5.200000
50%         6.200000
75%         6.400000
max         8.100000
Name: vlfoodsec_12_14, dtype: float64

In [58]:
insecurity.vlfoodsec_15_17.describe()

count    3143.000000
mean        5.098027
std         1.055067
min         2.900000
25%         4.100000
50%         5.100000
75%         5.800000
max         7.100000
Name: vlfoodsec_15_17, dtype: float64

In [59]:
insecurity.ch_vlfoodsec_14_17.describe()

count    3143.000000
mean       -0.817499
std         0.819079
min        -3.100000
25%        -1.300000
50%        -0.800000
75%        -0.400000
max         2.000000
Name: ch_vlfoodsec_14_17, dtype: float64

Negative values are acceptable here, as this column represents a change in percentage.

No -9999 values or other issues are apparent in observing summary statistics.

#####  Datatypes

In [60]:
insecurity.dtypes #shows datatypes of the columns

fips                    int64
state                  object
county                 object
foodinsec_12_14       float64
foodinsec_15_17       float64
ch_foodinsec_14_17    float64
vlfoodsec_12_14       float64
vlfoodsec_15_17       float64
ch_vlfoodsec_14_17    float64
dtype: object

These are the appropriate datatypes. As I mentioned, I will observe further during later analysis.  For now, the dataframe will be saved as-is.

### 3. Saving clean dataframe as a csv

In [61]:
insecurity.to_csv('../data/FoodEnvironmentAtlas.xls.INSECURITY_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## V. Food Atlas Environment - LOCAL

This dataset contains information regarding local farms within a community, including direct sales, farmer's markets, farm acreage, and much more.

### 1. Data Import

In [62]:
file_path = '../data/FoodEnvironmentAtlas.xls.LOCAL.csv'

local = pd.read_csv(file_path)

### 2. Preliminary Analysis & Cleaning

In [63]:
local.head() #shows top 5 rows of dataframe

FIPS State   County  DIRSALES_FARMS07  DIRSALES_FARMS12  \
0  1001.0    AL  Autauga              25.0              51.0   
1  1003.0    AL  Baldwin              80.0             103.0   
2  1005.0    AL  Barbour              18.0              13.0   
3  1007.0    AL     Bibb              12.0              13.0   
4  1009.0    AL   Blount              84.0              88.0   

   PCH_DIRSALES_FARMS_07_12  PCT_LOCLFARM07  PCT_LOCLFARM12  PCT_LOCLSALE07  \
0                104.000000        6.024096       13.110540        0.596374   
1                 28.750000        7.023705       10.414560        0.712634   
2                -27.777778        2.889246        2.276708        0.015403   
3                  8.333333        5.687204        6.878307             NaN   
4                  4.761905        5.940594        7.091056        0.267717   

   PCT_LOCLSALE12  ...  CSA12  PCH_CSA_07_12  AGRITRSM_OPS07  AGRITRSM_OPS12  \
0        1.554692  ...    3.0      50.000000             7.0            10.0   
1        0.478010  ...    7.0     -46.153846            18.0            16.0   
2        0.012457  ...    0.0    -100.000000            27.0            32.0   
3             NaN  ...    3.0      50.000000             5.0             6.0   
4        0.277792  ...    4.0     -42.857143            10.0             8.0   

   PCH_AGRITRSM_OPS_07_12  AGRITRSM_RCT07  AGRITRSM_RCT12  \
0               42.857143        228000.0        146000.0   
1              -11.111111        124000.0        204000.0   
2               18.518519        163000.0        304000.0   
3               20.000000             NaN         21000.0   
4              -20.000000        293000.0         30000.0   

   PCH_AGRITRSM_RCT_07_12  FARM_TO_SCHOOL13  FARM_TO_SCHOOL15  
0              -35.964912               NaN               0.0  
1               64.516129               0.0               1.0  
2               86.503067               1.0               0.0  
3                     NaN               0.0               0.0  
4              -89.761092               1.0               0.0  

[5 rows x 100 columns]

In [64]:
local.shape #shows layout of dataframe

(3144, 100)

There are 100 columns! I wonder what is most predictive out of these many features. I will explore further during EDA. What must be first assessed is the discrepancy between the number of rows in this dataset (3144) and the others.

There could be an empty row here. I will check the missing values.

In [65]:
local.isnull().sum() #shows number of missing values in each column

FIPS                         1
State                        1
County                       1
DIRSALES_FARMS07            64
DIRSALES_FARMS12            64
                          ... 
AGRITRSM_RCT07            1170
AGRITRSM_RCT12            1025
PCH_AGRITRSM_RCT_07_12    1877
FARM_TO_SCHOOL13           208
FARM_TO_SCHOOL15           219
Length: 100, dtype: int64

There are many missing values! During EDA, I will determine what needs to be filled, what can be dropped, and so on.

However, I do notice that one row is missing FIPS, state, and county. These are obviously essential pieces of information. I will observe the row for further information.

In [66]:
local.loc[local['County'].isnull()] #displays row that is missing the county name

FIPS State County  DIRSALES_FARMS07  DIRSALES_FARMS12  \
3143   NaN   NaN    NaN               NaN               NaN   

      PCH_DIRSALES_FARMS_07_12  PCT_LOCLFARM07  PCT_LOCLFARM12  \
3143                       NaN             NaN             NaN   

      PCT_LOCLSALE07  PCT_LOCLSALE12  ...  CSA12  PCH_CSA_07_12  \
3143             NaN             NaN  ...    NaN            NaN   

      AGRITRSM_OPS07  AGRITRSM_OPS12  PCH_AGRITRSM_OPS_07_12  AGRITRSM_RCT07  \
3143             NaN             NaN                     NaN             NaN   

      AGRITRSM_RCT12  PCH_AGRITRSM_RCT_07_12  FARM_TO_SCHOOL13  \
3143             NaN                     NaN          0.618399   

      FARM_TO_SCHOOL15  
3143               NaN  

[1 rows x 100 columns]

This row contains no county information, and will be dropped.

In [67]:
local = local.drop([local.index[3143]]) #drops row at index 3143 (displayed above)

local.shape #shows revised layout of dataframe

(3143, 100)

This now has the correct number of rows. I will compare this dataset to the Health dataset to ensure that they match.

In [68]:
local.tail() #shows last 5 rows of dataframe

FIPS State      County  DIRSALES_FARMS07  DIRSALES_FARMS12  \
3138  56037.0    WY  Sweetwater              15.0              22.0   
3139  56039.0    WY       Teton               4.0              11.0   
3140  56041.0    WY       Uinta              13.0              24.0   
3141  56043.0    WY    Washakie              25.0               5.0   
3142  56045.0    WY      Weston              15.0               3.0   

      PCH_DIRSALES_FARMS_07_12  PCT_LOCLFARM07  PCT_LOCLFARM12  \
3138                 46.666667        6.147541        8.627451   
3139                175.000000        2.222222        7.142857   
3140                 84.615385        3.779070        7.619048   
3141                -80.000000       11.682243        2.392344   
3142                -80.000000        6.329114        1.136364   

      PCT_LOCLSALE07  PCT_LOCLSALE12  ...  CSA12  PCH_CSA_07_12  \
3138        1.089204        0.444697  ...    0.0            NaN   
3139        0.021817        0.265604  ...    0.0            NaN   
3140             NaN        0.445308  ...    0.0         -100.0   
3141        0.154231             NaN  ...    1.0            NaN   
3142             NaN             NaN  ...    0.0            NaN   

      AGRITRSM_OPS07  AGRITRSM_OPS12  PCH_AGRITRSM_OPS_07_12  AGRITRSM_RCT07  \
3138             1.0             2.0              100.000000             NaN   
3139             5.0            12.0              140.000000       1614000.0   
3140             5.0             9.0               80.000000        105000.0   
3141             8.0             6.0              -25.000000         70000.0   
3142            14.0             9.0              -35.714286        147000.0   

      AGRITRSM_RCT12  PCH_AGRITRSM_RCT_07_12  FARM_TO_SCHOOL13  \
3138             NaN                     NaN               0.0   
3139             NaN                     NaN               0.0   
3140             NaN                     NaN               0.0   
3141         62000.0              -11.428571               0.0   
3142         71000.0              -51.700680               0.0   

      FARM_TO_SCHOOL15  
3138               0.0  
3139               0.0  
3140               0.0  
3141               0.0  
3142               0.0  

[5 rows x 100 columns]

In [69]:
health.tail() #shows last 5 rows of dataframe

fips state      county  pct_diabetes_adults08  pct_diabetes_adults13  \
3138  56037    WY  Sweetwater                    6.8                    8.1   
3139  56039    WY       Teton                    4.1                    4.8   
3140  56041    WY       Uinta                    6.3                    9.0   
3141  56043    WY    Washakie                   10.5                   12.0   
3142  56045    WY      Weston                    7.1                   10.0   

      pct_obese_adults12  pct_obese_adults17  pct_hspa17  recfac11  recfac16  \
3138                24.6                28.8         NaN         4         6   
3139                24.6                28.8         NaN         9        13   
3140                24.6                28.8         NaN         3         2   
3141                24.6                28.8         NaN         1         1   
3142                24.6                28.8         NaN         1         0   

      pch_recfac_11_16  recfacpth11  recfacpth16  pch_recfacpth_11_16  
3138         50.000000     0.090882     0.135609            49.213470  
3139         44.444444     0.419072     0.560828            33.826095  
3140        -33.333333     0.143548     0.096567           -32.728180  
3141          0.000000     0.118203     0.122130             3.321935  
3142       -100.000000     0.140036     0.000000          -100.000000

In [70]:
local.head() #shows top 5 rows of dataframe

FIPS State   County  DIRSALES_FARMS07  DIRSALES_FARMS12  \
0  1001.0    AL  Autauga              25.0              51.0   
1  1003.0    AL  Baldwin              80.0             103.0   
2  1005.0    AL  Barbour              18.0              13.0   
3  1007.0    AL     Bibb              12.0              13.0   
4  1009.0    AL   Blount              84.0              88.0   

   PCH_DIRSALES_FARMS_07_12  PCT_LOCLFARM07  PCT_LOCLFARM12  PCT_LOCLSALE07  \
0                104.000000        6.024096       13.110540        0.596374   
1                 28.750000        7.023705       10.414560        0.712634   
2                -27.777778        2.889246        2.276708        0.015403   
3                  8.333333        5.687204        6.878307             NaN   
4                  4.761905        5.940594        7.091056        0.267717   

   PCT_LOCLSALE12  ...  CSA12  PCH_CSA_07_12  AGRITRSM_OPS07  AGRITRSM_OPS12  \
0        1.554692  ...    3.0      50.000000             7.0            10.0   
1        0.478010  ...    7.0     -46.153846            18.0            16.0   
2        0.012457  ...    0.0    -100.000000            27.0            32.0   
3             NaN  ...    3.0      50.000000             5.0             6.0   
4        0.277792  ...    4.0     -42.857143            10.0             8.0   

   PCH_AGRITRSM_OPS_07_12  AGRITRSM_RCT07  AGRITRSM_RCT12  \
0               42.857143        228000.0        146000.0   
1              -11.111111        124000.0        204000.0   
2               18.518519        163000.0        304000.0   
3               20.000000             NaN         21000.0   
4              -20.000000        293000.0         30000.0   

   PCH_AGRITRSM_RCT_07_12  FARM_TO_SCHOOL13  FARM_TO_SCHOOL15  
0              -35.964912               NaN               0.0  
1               64.516129               0.0               1.0  
2               86.503067               1.0               0.0  
3                     NaN               0.0               0.0  
4              -89.761092               1.0               0.0  

[5 rows x 100 columns]

In [71]:
health.head() #shows top 5 rows of dataframe

fips state   county  pct_diabetes_adults08  pct_diabetes_adults13  \
0  1001    AL  Autauga                   11.4                   13.0   
1  1003    AL  Baldwin                    9.8                   10.4   
2  1005    AL  Barbour                   13.6                   18.4   
3  1007    AL     Bibb                   11.1                   14.8   
4  1009    AL   Blount                   11.4                   14.1   

   pct_obese_adults12  pct_obese_adults17  pct_hspa17  recfac11  recfac16  \
0                33.0                36.3         NaN         4         6   
1                33.0                36.3         NaN        16        21   
2                33.0                36.3         NaN         2         0   
3                33.0                36.3         NaN         0         1   
4                33.0                36.3         NaN         3         4   

   pch_recfac_11_16  recfacpth11  recfacpth16  pch_recfacpth_11_16  
0         50.000000     0.072465     0.108542            49.785629  
1         31.250000     0.085775     0.101200            17.983256  
2       -100.000000     0.073123     0.000000          -100.000000  
3               NaN     0.000000     0.044183                  NaN  
4         33.333333     0.052118     0.069490            33.333333

In [72]:
local.FIPS.describe() #shows a statistical summary of the fips codes

count     3143.000000
mean     30390.411709
std      15164.717720
min       1001.000000
25%      18178.000000
50%      29177.000000
75%      45082.000000
max      56045.000000
Name: FIPS, dtype: float64

In [73]:
health.fips.describe() #shows a statistical summary of the fips codes

count     3143.000000
mean     30390.411709
std      15164.717720
min       1001.000000
25%      18178.000000
50%      29177.000000
75%      45082.000000
max      56045.000000
Name: fips, dtype: float64

The top and bottom 5 rows of the 2 datasets show the same counties. The statistical summaries of the fips codes are identical. The number of rows is now the same in the 2 datasets.

It seems the discrepancy has been resolved. Next, I will make the columns in the Local dataset lowercase.

In [74]:
local.columns = [col.lower() for col in local.columns] #changes column names to all-lowercase

local.columns #shows revised column names

Index(['fips', 'state', 'county', 'dirsales_farms07', 'dirsales_farms12',
       'pch_dirsales_farms_07_12', 'pct_loclfarm07', 'pct_loclfarm12',
       'pct_loclsale07', 'pct_loclsale12', 'dirsales07', 'dirsales12',
       'pch_dirsales_07_12', 'pc_dirsales07', 'pc_dirsales12',
       'pch_pc_dirsales_07_12', 'fmrkt13', 'fmrkt18', 'pch_fmrkt_13_18',
       'fmrktpth13', 'fmrktpth18', 'pch_fmrktpth_13_18', 'fmrkt_snap18',
       'pct_fmrkt_snap18', 'fmrkt_wic18', 'pct_fmrkt_wic18', 'fmrkt_wiccash18',
       'pct_fmrkt_wiccash18', 'fmrkt_sfmnp18', 'pct_fmrkt_sfmnp18',
       'fmrkt_credit18', 'pct_fmrkt_credit18', 'fmrkt_frveg18',
       'pct_fmrkt_frveg18', 'fmrkt_anmlprod18', 'pct_fmrkt_anmlprod18',
       'fmrkt_baked18', 'pct_fmrkt_baked18', 'fmrkt_otherfood18',
       'pct_fmrkt_otherfood18', 'veg_farms07', 'veg_farms12',
       'pch_veg_farms_07_12', 'veg_acres07', 'veg_acres12',
       'pch_veg_acres_07_12', 'veg_acrespth07', 'veg_acrespth12',
       'pch_veg_acrespth_07_12', 'fre

This dataframe will be saved for now. As I mentioned, I will look into which missing values must be replaced and the best method for doing so.

### 3. Saving clean dataframe as a csv

In [75]:
local.to_csv('../data/FoodEnvironmentAtlas.xls.LOCAL_CLEAN.csv', index = False) #saves clean dataframe to a new csv

### VI. Food Environment Atlas - RESTAURANTS

This dataset contains information regarding number of restaurants and per capita spending on Full-Service and Fast Food restaurants.

### 1. Data Import

In [76]:
file_path = '../data/FoodEnvironmentAtlas.xls.RESTAURANTS.csv'

restaurants = pd.read_csv(file_path)

In [77]:
restaurants.head() #displays top 5 rows of dataframe

FIPS State   County  FFR11  FFR16  PCH_FFR_11_16  FFRPTH11  FFRPTH16  \
0  1001    AL  Autauga     34     44      29.411765  0.615953  0.795977   
1  1003    AL  Baldwin    121    156      28.925620  0.648675  0.751775   
2  1005    AL  Barbour     19     23      21.052632  0.694673  0.892372   
3  1007    AL     Bibb      6      7      16.666667  0.263794  0.309283   
4  1009    AL   Blount     20     23      15.000000  0.347451  0.399569   

   PCH_FFRPTH_11_16  FSR11  FSR16  PCH_FSR_11_16  FSRPTH11  FSRPTH16  \
0         29.226817     32     31      -3.125000  0.579721  0.560802   
1         15.893824    216    236       9.259259  1.157966  1.137300   
2         28.459320     17     14     -17.647059  0.621549  0.543183   
3         17.243995      5      7      40.000000  0.219829  0.309283   
4         15.000000     15     12     -20.000000  0.260589  0.208471   

   PCH_FSRPTH_11_16  PC_FFRSALES07  PC_FFRSALES12  PC_FSRSALES07  \
0         -3.263448     649.511367      674.80272     484.381507   
1         -1.784662     649.511367      674.80272     484.381507   
2        -12.608237     649.511367      674.80272     484.381507   
3         40.692794     649.511367      674.80272     484.381507   
4        -20.000000     649.511367      674.80272     484.381507   

   PC_FSRSALES12  
0     512.280987  
1     512.280987  
2     512.280987  
3     512.280987  
4     512.280987

In [78]:
restaurants.shape #shows layout of dataframe

(3143, 19)

With only 19 columns, I will retain the full dataset for now.

I am particularly interested to see how the number of fast food restaurants might impact prevalence of diabetes.

In [79]:
restaurants.dtypes

FIPS                  int64
State                object
County               object
FFR11                 int64
FFR16                 int64
PCH_FFR_11_16       float64
FFRPTH11            float64
FFRPTH16            float64
PCH_FFRPTH_11_16    float64
FSR11                 int64
FSR16                 int64
PCH_FSR_11_16       float64
FSRPTH11            float64
FSRPTH16            float64
PCH_FSRPTH_11_16    float64
PC_FFRSALES07       float64
PC_FFRSALES12       float64
PC_FSRSALES07       float64
PC_FSRSALES12       float64
dtype: object

These all seem to be the appropriate datatypes.

In [80]:
restaurants.isnull().sum() #shows the number of missing values per column

FIPS                 0
State                0
County               0
FFR11                0
FFR16                0
PCH_FFR_11_16       57
FFRPTH11             0
FFRPTH16             0
PCH_FFRPTH_11_16    52
FSR11                0
FSR16                0
PCH_FSR_11_16       28
FSRPTH11             0
FSRPTH16             0
PCH_FSRPTH_11_16    23
PC_FFRSALES07        0
PC_FFRSALES12        0
PC_FSRSALES07        0
PC_FSRSALES12        0
dtype: int64

The only missing values are in columns with calculated percent changes - since the respective 2011 and 2016 columns are complete, I can use the information to derive the percent changes.

I will remove the percent change columns after I make the columns lowercase.

In [81]:
restaurants.columns = [col.lower() for col in restaurants.columns] #makes the columns lowercase

restaurants.columns #displays revised column names

Index(['fips', 'state', 'county', 'ffr11', 'ffr16', 'pch_ffr_11_16',
       'ffrpth11', 'ffrpth16', 'pch_ffrpth_11_16', 'fsr11', 'fsr16',
       'pch_fsr_11_16', 'fsrpth11', 'fsrpth16', 'pch_fsrpth_11_16',
       'pc_ffrsales07', 'pc_ffrsales12', 'pc_fsrsales07', 'pc_fsrsales12'],
      dtype='object')

In [82]:
#drops the percent change columns

restaurants = restaurants.drop(columns = ['pch_ffr_11_16', 'pch_ffrpth_11_16', 'pch_fsr_11_16', 'pch_fsrpth_11_16'])

restaurants.isnull().sum() #displays the revised list of columns with count of missing values

fips             0
state            0
county           0
ffr11            0
ffr16            0
ffrpth11         0
ffrpth16         0
fsr11            0
fsr16            0
fsrpth11         0
fsrpth16         0
pc_ffrsales07    0
pc_ffrsales12    0
pc_fsrsales07    0
pc_fsrsales12    0
dtype: int64

The respective columns and missing values have been removed.

I will observe summary statistics for the numerical columns to observe for issues.

In [83]:
restaurants.fips.describe()

count     3143.000000
mean     30390.411709
std      15164.717720
min       1001.000000
25%      18178.000000
50%      29177.000000
75%      45082.000000
max      56045.000000
Name: fips, dtype: float64

In [84]:
restaurants.ffr11.describe()

count    3143.000000
mean       68.797327
std       237.039266
min         0.000000
25%         5.000000
50%        15.000000
75%        42.500000
max      7211.000000
Name: ffr11, dtype: float64

In [85]:
restaurants.ffr16.describe()

count    3143.000000
mean       75.696787
std       268.845823
min         0.000000
25%         5.000000
50%        15.000000
75%        45.000000
max      8264.000000
Name: ffr16, dtype: float64

In [86]:
restaurants.ffrpth11.describe()

count    3143.000000
mean        0.560159
std         0.301338
min         0.000000
25%         0.395000
50%         0.562491
75%         0.709595
max         5.797101
Name: ffrpth11, dtype: float64

In [87]:
restaurants.ffrpth16.describe()

count    3143.000000
mean        0.584822
std         0.307703
min         0.000000
25%         0.418769
50%         0.588565
75%         0.748136
max         5.805515
Name: ffrpth16, dtype: float64

In [88]:
restaurants.fsr11.describe()

count    3143.00000
mean       72.26917
std       239.76644
min         0.00000
25%         7.00000
50%        17.00000
75%        48.00000
max      7125.00000
Name: fsr11, dtype: float64

In [89]:
restaurants.fsr16.describe()

count    3143.000000
mean       78.551066
std       269.993476
min         0.000000
25%         7.000000
50%        18.000000
75%        48.000000
max      8113.000000
Name: fsr16, dtype: float64

In [90]:
restaurants.fsrpth11.describe()

count    3143.000000
mean        0.772666
std         0.594496
min         0.000000
25%         0.492174
50%         0.665266
75%         0.893799
max        15.942029
Name: fsrpth11, dtype: float64

In [91]:
restaurants.fsrpth16.describe()

count    3143.000000
mean        0.775831
std         0.567851
min         0.000000
25%         0.495050
50%         0.672495
75%         0.894307
max        11.611030
Name: fsrpth16, dtype: float64

In [92]:
restaurants.pc_ffrsales07.describe()

count    3143.000000
mean      641.617910
std        96.641980
min       402.097804
25%       576.210444
50%       632.337378
75%       721.823151
max      1043.860861
Name: pc_ffrsales07, dtype: float64

In [93]:
restaurants.pc_ffrsales12.describe()

count    3143.000000
mean      599.639926
std        78.735909
min       364.112002
25%       530.267589
50%       611.294779
75%       650.723556
max      1035.391608
Name: pc_ffrsales12, dtype: float64

In [94]:
restaurants.pc_fsrsales07.describe()

count    3143.000000
mean      624.523725
std       128.070842
min       371.845051
25%       534.383583
50%       617.339006
75%       711.769798
max      1930.155806
Name: pc_fsrsales07, dtype: float64

In [95]:
restaurants.pc_ffrsales12.describe()

count    3143.000000
mean      599.639926
std        78.735909
min       364.112002
25%       530.267589
50%       611.294779
75%       650.723556
max      1035.391608
Name: pc_ffrsales12, dtype: float64

In [96]:
restaurants.pc_fsrsales07.describe()

count    3143.000000
mean      624.523725
std       128.070842
min       371.845051
25%       534.383583
50%       617.339006
75%       711.769798
max      1930.155806
Name: pc_fsrsales07, dtype: float64

In [97]:
restaurants.pc_fsrsales12.describe()

count    3143.000000
mean      651.969675
std       116.536765
min       439.731454
25%       573.685136
50%       643.144903
75%       697.649988
max      2160.503105
Name: pc_fsrsales12, dtype: float64

I see no -9999 values or other issues here. The cleaned dataframe will be saved as a csv.

### 3. Saving clean dataframe to a csv

In [98]:
restaurants.to_csv('../data/FoodEnvironmentAtlas.xls.RESTAURANTS_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## VII. Food Environment - SOCIOECONOMIC

This dataset contains information regarding poverty, ethnicity, and metroplolitan description of the counties.

### 1. Data Import

In [99]:
file_path = '../data/FoodEnvironmentAtlas.xls.SOCIOECONOMIC.csv'

socioeconomic = pd.read_csv(file_path)

### 2. Preliminary Data Analysis & Cleaning

In [100]:
socioeconomic.head() #shows first 5 rows of dataframe

FIPS State   County  PCT_NHWHITE10  PCT_NHBLACK10  PCT_HISP10  \
0  1001    AL  Autauga      77.246156      17.582599    2.400542   
1  1003    AL  Baldwin      83.504787       9.308425    4.384824   
2  1005    AL  Barbour      46.753105      46.691190    5.051535   
3  1007    AL     Bibb      75.020729      21.924504    1.771765   
4  1009    AL   Blount      88.887338       1.263040    8.070200   

   PCT_NHASIAN10  PCT_NHNA10  PCT_NHPI10  PCT_65OLDER10  PCT_18YOUNGER10  \
0       0.855766    0.397647    0.040314      11.995382        26.777959   
1       0.735193    0.628755    0.043343      16.771185        22.987408   
2       0.389700    0.218524    0.087409      14.236807        21.906982   
3       0.096007    0.279293    0.030548      12.681650        22.696923   
4       0.200621    0.497191    0.031402      14.722096        24.608353   

   MEDHHINC15  POVRATE15  PERPOV10  CHILDPOVRATE15  PERCHLDPOV10  METRO13  \
0     56580.0       12.7         0            18.8             0        1   
1     52387.0       12.9         0            19.6             0        1   
2     31433.0       32.0         1            45.2             1        0   
3     40767.0       22.2         0            29.3             1        1   
4     50487.0       14.7         0            22.2             0        1   

   POPLOSS10  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0

In [101]:
socioeconomic.dtypes #shows the datatype of each column

FIPS                 int64
State               object
County              object
PCT_NHWHITE10      float64
PCT_NHBLACK10      float64
PCT_HISP10         float64
PCT_NHASIAN10      float64
PCT_NHNA10         float64
PCT_NHPI10         float64
PCT_65OLDER10      float64
PCT_18YOUNGER10    float64
MEDHHINC15         float64
POVRATE15          float64
PERPOV10             int64
CHILDPOVRATE15     float64
PERCHLDPOV10         int64
METRO13              int64
POPLOSS10          float64
dtype: object

The datatypes seem appropriate, as expected.

In [102]:
socioeconomic.isnull().sum() #shows missing values in each column

FIPS               0
State              0
County             0
PCT_NHWHITE10      0
PCT_NHBLACK10      0
PCT_HISP10         0
PCT_NHASIAN10      0
PCT_NHNA10         0
PCT_NHPI10         0
PCT_65OLDER10      0
PCT_18YOUNGER10    0
MEDHHINC15         4
POVRATE15          4
PERPOV10           0
CHILDPOVRATE15     4
PERCHLDPOV10       0
METRO13            0
POPLOSS10          2
dtype: int64

This is a small number of missing values. Missing values entered as "-9999" will be explored at a later time.

I will revise the column names to make all letters lowercase.

In [103]:
socioeconomic.columns = [col.lower() for col in socioeconomic.columns] #makes letters in column names lowercase

socioeconomic.columns #shows revised column names

Index(['fips', 'state', 'county', 'pct_nhwhite10', 'pct_nhblack10',
       'pct_hisp10', 'pct_nhasian10', 'pct_nhna10', 'pct_nhpi10',
       'pct_65older10', 'pct_18younger10', 'medhhinc15', 'povrate15',
       'perpov10', 'childpovrate15', 'perchldpov10', 'metro13', 'poploss10'],
      dtype='object')

The column names have been revised.

Meanwhile, I am uncertain about how I feel about making predictions based on the ethnic makeup of the population...

While measures can be taken to improve people's access to certain foods, stores, financial resources and so on, it is not possible (or necessary) to change people's ethnicity.

What I would like to avoid is predicting county prevalence of diabetes based on ethnicity, as someone might decide that the prevalence is high in some areas due to having too many of "those" people living there.

I will remove the columns pertaining to ethnicity.

In [104]:
#removes ethnicity columns

socioeconomic = socioeconomic.drop(columns = ['pct_nhwhite10', 'pct_nhblack10', 'pct_hisp10', 
                                              'pct_nhasian10', 'pct_nhna10', 'pct_nhpi10'])

socioeconomic.columns #shows revised list of columns

Index(['fips', 'state', 'county', 'pct_65older10', 'pct_18younger10',
       'medhhinc15', 'povrate15', 'perpov10', 'childpovrate15', 'perchldpov10',
       'metro13', 'poploss10'],
      dtype='object')

I will now observe summary statistics of the numerical columns to look for any issues.

In [105]:
socioeconomic.fips.describe()

count     3143.000000
mean     30390.411709
std      15164.717720
min       1001.000000
25%      18178.000000
50%      29177.000000
75%      45082.000000
max      56045.000000
Name: fips, dtype: float64

In [106]:
socioeconomic.pct_65older10.describe()

count    3143.000000
mean       15.882540
std         4.190210
min         3.470599
25%        13.122703
50%        15.568674
75%        18.204279
max        43.384714
Name: pct_65older10, dtype: float64

In [107]:
socioeconomic.pct_18younger10.describe()

count    3143.000000
mean       23.419345
std         3.375268
min         0.000000
25%        21.429605
50%        23.327538
75%        25.102898
max        41.573938
Name: pct_18younger10, dtype: float64

In [108]:
socioeconomic.medhhinc15.describe()

count      3139.000000
mean      48611.206117
std       12351.988288
min       22894.000000
25%       40438.000000
50%       46807.000000
75%       54164.000000
max      125900.000000
Name: medhhinc15, dtype: float64

In [109]:
socioeconomic.povrate15.describe()

count    3139.000000
mean       16.260975
std         6.442319
min         3.400000
25%        11.500000
50%        15.200000
75%        19.700000
max        47.400000
Name: povrate15, dtype: float64

In [110]:
socioeconomic.perpov10.describe()

count    3143.000000
mean        0.112313
std         0.315801
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: perpov10, dtype: float64

In [111]:
socioeconomic.childpovrate15.describe()

count    3139.000000
mean       23.238738
std         9.364172
min         3.300000
25%        16.250000
50%        22.300000
75%        29.100000
max        61.600000
Name: childpovrate15, dtype: float64

In [112]:
socioeconomic.perchldpov10.describe()

count    3143.000000
mean        0.225262
std         0.417822
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: perchldpov10, dtype: float64

In [113]:
socioeconomic.metro13.describe()

count    3143.000000
mean        0.371301
std         0.483230
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: metro13, dtype: float64

In [114]:
socioeconomic.poploss10.describe()

count    3141.000000
mean        0.168418
std         0.374296
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: poploss10, dtype: float64

In [115]:
socioeconomic.dtypes

fips                 int64
state               object
county              object
pct_65older10      float64
pct_18younger10    float64
medhhinc15         float64
povrate15          float64
perpov10             int64
childpovrate15     float64
perchldpov10         int64
metro13              int64
poploss10          float64
dtype: object

There are a small number of missing values in some columns as noted earlier, but no -9999 values or other issues.

The dataframe is sufficiently clean, and I will save it as a csv.

### 3. Saving cleaned dataframe as a csv

In [116]:
socioeconomic.to_csv('../data/FoodEnvironmentAtlas.xls.SOCIOECONOMIC_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## VII. Food Environment Atlas - STORES 

This dataset contains information regarding the numbers and types of food stores within the counties.

### 1. Data Import

In [117]:
file_path = '../data/FoodEnvironmentAtlas.xls.STORES.csv'

stores = pd.read_csv(file_path)

### 2. Preliminary Data Analysis & Cleaning

In [118]:
stores.head() #displays top 5 rows of dataframe

FIPS State   County  GROC11  GROC16  PCH_GROC_11_16  GROCPTH11  GROCPTH16  \
0  1001    AL  Autauga       5       3      -40.000000   0.090581   0.054271   
1  1003    AL  Baldwin      27      29        7.407407   0.144746   0.139753   
2  1005    AL  Barbour       6       4      -33.333333   0.219370   0.155195   
3  1007    AL     Bibb       6       5      -16.666667   0.263794   0.220916   
4  1009    AL   Blount       7       5      -28.571429   0.121608   0.086863   

   PCH_GROCPTH_11_16  SUPERC11  ...  PCH_SNAPS_12_17  SNAPSPTH12  SNAPSPTH17  \
0         -40.085748         1  ...        19.376392    0.674004    0.804747   
1          -3.449328         6  ...        36.927711    0.725055    0.890836   
2         -29.254287         0  ...         3.349282    1.280590    1.424614   
3         -16.254289         1  ...        11.794872    0.719122    0.801423   
4         -28.571429         1  ...         5.701754    0.657144    0.692374   

   PCH_SNAPSPTH_12_17  WICS11  WICS16  PCH_WICS_11_16  WICSPTH11  WICSPTH16  \
0           19.397900     5.0     5.0        0.000000   0.090567   0.090511   
1           22.864524    26.0    28.0        7.692307   0.139380   0.134802   
2           11.246689     7.0     6.0      -14.285714   0.255942   0.232387   
3           11.444711     6.0     5.0      -16.666666   0.263771   0.221474   
4            5.361034     8.0     8.0        0.000000   0.139000   0.139089   

   PCH_WICSPTH_11_16  
0          -0.061543  
1          -3.284727  
2          -9.203081  
3         -16.035471  
4           0.064332  

[5 rows x 39 columns]

In [119]:
stores.shape #displays layout of dataframe

(3143, 39)

In [120]:
stores.dtypes #shows datatypes of each column

FIPS                     int64
State                   object
County                  object
GROC11                   int64
GROC16                   int64
PCH_GROC_11_16         float64
GROCPTH11              float64
GROCPTH16              float64
PCH_GROCPTH_11_16      float64
SUPERC11                 int64
SUPERC16                 int64
PCH_SUPERC_11_16       float64
SUPERCPTH11            float64
SUPERCPTH16            float64
PCH_SUPERCPTH_11_16    float64
CONVS11                  int64
CONVS16                  int64
PCH_CONVS_11_16        float64
CONVSPTH11             float64
CONVSPTH16             float64
PCH_CONVSPTH_11_16     float64
SPECS11                  int64
SPECS16                  int64
PCH_SPECS_11_16        float64
SPECSPTH11             float64
SPECSPTH16             float64
PCH_SPECSPTH_11_16     float64
SNAPS12                float64
SNAPS17                float64
PCH_SNAPS_12_17        float64
SNAPSPTH12             float64
SNAPSPTH17             float64
PCH_SNAP

The datatypes seem appropriate. As with some of the previous dimensions of food environment, I think I may not need all of these columns.

A decision will be formulated when the time come. For now, I will leave the information intact. I will, however, make the column names lowercase for ease of use before saving the revised dataframe.

In [121]:
stores.columns = [col.lower() for col in stores.columns] #makes all letters in column names lowercase

stores.columns #shows revised column names

Index(['fips', 'state', 'county', 'groc11', 'groc16', 'pch_groc_11_16',
       'grocpth11', 'grocpth16', 'pch_grocpth_11_16', 'superc11', 'superc16',
       'pch_superc_11_16', 'supercpth11', 'supercpth16', 'pch_supercpth_11_16',
       'convs11', 'convs16', 'pch_convs_11_16', 'convspth11', 'convspth16',
       'pch_convspth_11_16', 'specs11', 'specs16', 'pch_specs_11_16',
       'specspth11', 'specspth16', 'pch_specspth_11_16', 'snaps12', 'snaps17',
       'pch_snaps_12_17', 'snapspth12', 'snapspth17', 'pch_snapspth_12_17',
       'wics11', 'wics16', 'pch_wics_11_16', 'wicspth11', 'wicspth16',
       'pch_wicspth_11_16'],
      dtype='object')

### 3. Saving clean dataframe as a csv

In [122]:
stores.to_csv('../data/FoodEnvironmentAtlas.xls.STORES_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## VIII. Food Environment Atlas - Supplemental Data - COUNTY

According to the README, this dataset contains information that was used for determining the percentages used in the other datasets. Specifically, these appear to be population estimates from 2010 - 2018 for each of the counties.

### 1. Data Import

In [123]:
file_path = '../data/FoodEnvironmentAtlas.xls.Supplemental_Data_County.csv'

supp_county = pd.read_csv(file_path)

### 2. Preliminary Data Analysis & Cleaning

In [124]:
supp_county.head() #shows top 5 rows of dataframe

FIPS          County     State 2010_Census_Population  \
0  1001  Autauga County   Alabama                 54,571   
1  1003  Baldwin County   Alabama                182,265   
2  1005  Barbour County   Alabama                 27,457   
3  1007     Bibb County   Alabama                 22,915   
4  1009   Blount County   Alabama                 57,322   

  Population_Estimate_2011 Population_Estimate_2012 Population_Estimate_2013  \
0                   55,208                   54,936                   54,713   
1                  186,540                  190,143                  194,886   
2                   27,350                   27,174                   26,944   
3                   22,747                   22,664                   22,516   
4                   57,554                   57,570                   57,611   

  Population_Estimate_2014 Population_Estimate_2015 Population_Estimate_2016  \
0                   54,876                   54,838                   55,242   
1                  199,189                  202,995                  207,712   
2                   26,758                   26,294                   25,819   
3                   22,541                   22,562                   22,576   
4                   57,521                   57,522                   57,517   

  Population_Estimate_2017 Population_Estimate_2018  
0                   55,443                   55,601  
1                  212,619                  218,022  
2                   25,158                   24,881  
3                   22,555                   22,400  
4                   57,827                   57,840

In [125]:
supp_county.shape #shows the layout of the dataframe

(3142, 12)

In [126]:
supp_county.columns #displays column names

Index(['FIPS', 'County', 'State', '2010_Census_Population',
       'Population_Estimate_2011', 'Population_Estimate_2012',
       'Population_Estimate_2013', 'Population_Estimate_2014',
       'Population_Estimate_2015', 'Population_Estimate_2016',
       'Population_Estimate_2017', 'Population_Estimate_2018'],
      dtype='object')

The reason my target is the diabetes prevalence in 2018 is because the data seem to go through 2018 (approximately 2010 - 2018, which is reflected in the column names here.)

In [127]:
supp_county.isnull().sum() #displays the number of missing values per column

FIPS                        0
County                      0
State                       0
2010_Census_Population      0
Population_Estimate_2011    0
Population_Estimate_2012    0
Population_Estimate_2013    0
Population_Estimate_2014    0
Population_Estimate_2015    0
Population_Estimate_2016    0
Population_Estimate_2017    0
Population_Estimate_2018    0
dtype: int64

There are no blank values, though missing values may have been filled in with "-9999."

It is unlikely that I will analyze or utilize this information moving forward, but may reference it if needed at a later time. For now, I will simply make the columns lowercase, and save the revised dataframe as a CSV.

In [128]:
supp_county.columns = [col.lower() for col in supp_county.columns] #changes column names to lowercase

supp_county.columns #shows revised column names

Index(['fips', 'county', 'state', '2010_census_population',
       'population_estimate_2011', 'population_estimate_2012',
       'population_estimate_2013', 'population_estimate_2014',
       'population_estimate_2015', 'population_estimate_2016',
       'population_estimate_2017', 'population_estimate_2018'],
      dtype='object')

### 3. Saving dataframe as a csv

In [129]:
supp_county.to_csv('../data/FoodEnvironmentAtlas.xls.SUPP_COUNTY_CLEAN.csv', index = False) #saves clean dataframe to a new csv

### IX. Food Environment Atlas -  Supplemental Data - STATE

This dataset contains raw numbers of participants in some of the State programs, such as WIC, and state populations for some of the years within the Food Environment Atlas.

### 1. Data Import

In [130]:
file_path = '../data/FoodEnvironmentAtlas.xls.Supplemental_Data_State.csv'

supp_state = pd.read_csv(file_path)

### 2. Preliminary Analysis & Cleaning

In [131]:
supp_state.head() #shows top 5 rows of dataframe

StateFIPS       State WIC_PART_2012 WIC_PART_2013 WIC_PART_2014  \
0          1     Alabama       141,900       139,001       131,046   
1          2      Alaska        24,969        23,055        19,605   
2          4     Arizona       193,214       182,501       173,020   
3          5    Arkansas        94,293        89,777        83,289   
4          6  California     1,472,468     1,431,881     1,348,939   

  WIC_PART_2015 WIC_PART_2016 WIC_PART_2017 WIC_PART_2018 NSLP_PART_2012  ...  \
0       132,133       129,160       123,993       120,605        562,959  ...   
1        19,682        19,121        18,188        17,092         53,920  ...   
2       167,072       163,998       153,510       149,513        662,440  ...   
3        84,220        80,555        76,519        73,607        348,909  ...   
4     1,265,005     1,174,875     1,080,241     1,009,492      3,355,494  ...   

  SFSP_PART_2016 SFSP_PART_2017 SFSP_PART_2018 State_Population_2012  \
0         48,691         51,622         51,222             4,815,564   
1          4,688          4,959          4,266               730,399   
2         13,924         12,301         14,701             6,556,629   
3         35,767         23,544         18,211             2,952,109   
4        123,477        152,251        144,780            37,960,782   

  State_Population_2013 State_Population_2014 State_Population_2015  \
0             4,830,460             4,842,481             4,853,160   
1               737,045               736,307               737,547   
2             6,634,999             6,733,840             6,833,596   
3             2,959,549             2,967,726             2,978,407   
4            38,280,824            38,625,139            38,953,142   

  State_Population_2016 State_Population_2017 State_Population_2018  
0             4,864,745             4,875,120             4,887,871  
1               741,504               739,786               737,438  
2             6,945,452             7,048,876             7,171,646  
3             2,990,410             3,002,997             3,013,825  
4            39,209,127            39,399,349            39,557,045  

[5 rows x 44 columns]

Most of the factors in the dataset are on the county level, which is why I am predicting prevalence of diabetes on the county level...

However, it is possible that the state information could be used somehow.

I will reflect on this further as I continue to observe the data.

In [132]:
supp_state.shape #shows layout of the dataframe

(51, 44)

In [133]:
supp_state.isnull().sum() #shows number of missing values per column

StateFIPS                0
State                    0
WIC_PART_2012            0
WIC_PART_2013            0
WIC_PART_2014            0
WIC_PART_2015            0
WIC_PART_2016            0
WIC_PART_2017            0
WIC_PART_2018            0
NSLP_PART_2012           0
NSLP_PART_2013           0
NSLP_PART_2014           0
NSLP_PART_2015           0
NSLP_PART_2016           0
NSLP_PART_2017           0
NSLP_PART_2018           0
SBP_PART_2012            0
SBP_PART_2013            0
SBP_PART_2014            0
SBP_PART_2015            0
SBP_PART_2016            0
SBP_PART_2017            0
SBP_PART_2018            0
CACFP_PART_2012          0
CACFP_PART_2013          0
CACFP_PART_2014          0
CACFP_PART_2015          0
CACFP_PART_2016          0
CACFP_PART_2017          0
CACFP_PART_2018          0
SFSP_PART_2012           0
SFSP_PART_2013           0
SFSP_PART_2014           0
SFSP_PART_2015           0
SFSP_PART_2016           0
SFSP_PART_2017           0
SFSP_PART_2018           0
S

In looking through the columns, I am fairly certain that I will not use all of these.

It is possible that I might add some of the 2018 columns, such as WIC, to other datasets to use in model creation.

In [134]:
supp_state.dtypes #shows the datatypes for each column

StateFIPS                 int64
State                    object
WIC_PART_2012            object
WIC_PART_2013            object
WIC_PART_2014            object
WIC_PART_2015            object
WIC_PART_2016            object
WIC_PART_2017            object
WIC_PART_2018            object
NSLP_PART_2012           object
NSLP_PART_2013           object
NSLP_PART_2014           object
NSLP_PART_2015           object
NSLP_PART_2016           object
NSLP_PART_2017           object
NSLP_PART_2018           object
SBP_PART_2012            object
SBP_PART_2013            object
SBP_PART_2014            object
SBP_PART_2015            object
SBP_PART_2016            object
SBP_PART_2017            object
SBP_PART_2018            object
CACFP_PART_2012          object
CACFP_PART_2013          object
CACFP_PART_2014          object
CACFP_PART_2015          object
CACFP_PART_2016          object
CACFP_PART_2017          object
CACFP_PART_2018          object
SFSP_PART_2012           object
SFSP_PAR

For now, I will simply change the column names to lowercase, then save the revised dataframe as a csv.

In [135]:
supp_state.columns = [col.lower() for col in supp_state.columns] #changes column names to lowercase

supp_state.columns #shows revised column names

Index(['statefips', 'state', 'wic_part_2012', 'wic_part_2013', 'wic_part_2014',
       'wic_part_2015', 'wic_part_2016', 'wic_part_2017', 'wic_part_2018',
       'nslp_part_2012', 'nslp_part_2013', 'nslp_part_2014', 'nslp_part_2015',
       'nslp_part_2016', 'nslp_part_2017', 'nslp_part_2018', 'sbp_part_2012',
       'sbp_part_2013', 'sbp_part_2014', 'sbp_part_2015', 'sbp_part_2016',
       'sbp_part_2017', 'sbp_part_2018', 'cacfp_part_2012', 'cacfp_part_2013',
       'cacfp_part_2014', 'cacfp_part_2015', 'cacfp_part_2016',
       'cacfp_part_2017', 'cacfp_part_2018', 'sfsp_part_2012',
       'sfsp_part_2013', 'sfsp_part_2014', 'sfsp_part_2015', 'sfsp_part_2016',
       'sfsp_part_2017', 'sfsp_part_2018', 'state_population_2012',
       'state_population_2013', 'state_population_2014',
       'state_population_2015', 'state_population_2016',
       'state_population_2017', 'state_population_2018'],
      dtype='object')

### 3. Saving clean dataframe to a csv

In [136]:
supp_state.to_csv('../data/FoodEnvironmentAtlas.xls.SUPP_STATE_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## X. Food Environment Atlas - TAXES

This dataset contains information regarding taxes on overall food, along with chips and soda.

I will oberve for any issues.

### 1. Data Import

In [137]:
file_path = '../data/FoodEnvironmentAtlas.xls.TAXES.csv'

taxes = pd.read_csv(file_path)

### 2. Preliminary Data Analysis & Cleaning

In [138]:
taxes.head(10) #shows top 10 rows of dataframe

FIPS State    County  SODATAX_STORES14  SODATAX_VENDM14  CHIPSTAX_STORES14  \
0  1001    AL   Autauga               4.0              4.0                4.0   
1  1003    AL   Baldwin               4.0              4.0                4.0   
2  1005    AL   Barbour               4.0              4.0                4.0   
3  1007    AL      Bibb               4.0              4.0                4.0   
4  1009    AL    Blount               4.0              4.0                4.0   
5  1011    AL   Bullock               4.0              4.0                4.0   
6  1013    AL    Butler               4.0              4.0                4.0   
7  1015    AL   Calhoun               4.0              4.0                4.0   
8  1017    AL  Chambers               4.0              4.0                4.0   
9  1019    AL  Cherokee               4.0              4.0                4.0   

   CHIPSTAX_VENDM14  FOOD_TAX14  
0               4.0         4.0  
1               4.0         4.0  
2               4.0         4.0  
3               4.0         4.0  
4               4.0         4.0  
5               4.0         4.0  
6               4.0         4.0  
7               4.0         4.0  
8               4.0         4.0  
9               4.0         4.0

In looking through the data, it appears that the tax information is by state as opposed to county (which makes sense.) However, it could still be beneficial (and interesting) to know how taxes placed on certain food items impacts the prevalence of diabetes (with, I suppose, the intermediary of consumption of the food items.) 

In [139]:
taxes.shape #shows the layout of the dataframe

(3143, 8)

Eight is a refreshing number of columns- not overwhelming.

In [140]:
taxes.isnull().sum() #shows the number of missing values per column

FIPS                 0
State                0
County               0
SODATAX_STORES14     0
SODATAX_VENDM14      0
CHIPSTAX_STORES14    0
CHIPSTAX_VENDM14     0
FOOD_TAX14           0
dtype: int64

There are no blank values, though missing values could be entered as "-9999." 

This will be explored later (if I do use this dataset at all...)

In [141]:
taxes.dtypes #shows the datatype of each column

FIPS                   int64
State                 object
County                object
SODATAX_STORES14     float64
SODATAX_VENDM14      float64
CHIPSTAX_STORES14    float64
CHIPSTAX_VENDM14     float64
FOOD_TAX14           float64
dtype: object

These seem to be the appropriate datatypes. The column names will be changed to lowercase, and then the cleaned dataframe will be saved as a csv.

In [142]:
taxes.columns = [col.lower() for col in taxes.columns] #changes column names to lowercase

taxes.columns #shows revised column names

Index(['fips', 'state', 'county', 'sodatax_stores14', 'sodatax_vendm14',
       'chipstax_stores14', 'chipstax_vendm14', 'food_tax14'],
      dtype='object')

### 3. Saving cleaned dataframe to a csv

In [143]:
taxes.to_csv('../data/FoodEnvironmentAtlas.xls.TAXES_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## XI. Diabetes Atlas Data - 2018

This is the dataset from which I intend to draw out the target values - the prevalence of diabetes in adults (2018 values). While it can be difficult to determine from the source above that the 2018 values pertain to adults only, see  [here](https://www.cdc.gov/media/releases/2020/p1117-diabetes-surveillance-system.html) and [here](https://www.cdc.gov/diabetes/data/statistics/faqs.html) (*Question: "Do you have county-level estimates of obesity and diabetes in children and adolescents?)* for confirmation.

I will make an initial observation and cleaning of the data.

#### 1. Data Import

In [144]:
#imports data

file_path = '../data/DiabetesAtlasDataRT.csv'

d18 = pd.read_csv(file_path)

In [145]:
d18.head() #shows top 5 rows of dataframe

Year  County_FIPS          County    State  Diagnosed Diabetes Percentage  \
0  2018       1001.0  Autauga County  Alabama                            9.5   
1  2018       1003.0  Baldwin County  Alabama                            8.4   
2  2018       1005.0  Barbour County  Alabama                           13.5   
3  2018       1007.0     Bibb County  Alabama                           10.2   
4  2018       1009.0   Blount County  Alabama                           10.5   

   Overall SVI  
0       0.4354  
1       0.2162  
2       0.9959  
3       0.6003  
4       0.4242

### 2. Preliminary Analysis and Cleaning

In [146]:
d18.shape #shows the layout of the dataframe

(3142, 6)

In [147]:
d18.columns #shows list of columns

Index(['Year', 'County_FIPS', 'County', 'State',
       'Diagnosed Diabetes Percentage', 'Overall SVI'],
      dtype='object')

One of the first things I notice is an "Overall SVI." According to [this website](https://www.atsdr.cdc.gov/placeandhealth/svi/at-a-glance_svi.html), SVI stands for "Social Vulnerability Index" and is a score that includes factors pertaining to socioeconomic status, ethnicity, household status and others.

Within the Food Environment Atlas, there are many other columns pertaining  socioeconomic status, ethnicity, and related information. The SVI column is not needed, and will be removed.

First, however, I will make the columns lowercase.

In [148]:
d18.columns = [col.lower() for col in d18.columns]

The 'overall svi' column will now be removed. At this time, I will also remove the 'year' column, as all data is from 2018. However, I will first ensure that this is the case.

In [149]:
d18.year.unique() #shows unique values in this column

array(['2018',
       'US Diabetes Surveillance System; www.cdc.gov/diabetes/data; Division of Diabetes Translation - Centers for Disease Control and Prevention.'],
      dtype=object)

It appears that 2018 is the only year present, however there is additional information pertaining to the data download.

That factor will be assessed later. First, I will remove the necessary columns: year, and overall svi.

In [150]:
d18 = d18.drop(columns = ['year', 'overall svi'])

d18.columns

Index(['county_fips', 'county', 'state', 'diagnosed diabetes percentage'], dtype='object')

The columns were successfully dropped.

At this time, I notice other changes are needed to the columns, so I will make these now.

Below, I will edit the 'diagnosed diabetes percentage' to remove the spaces and make it shorter. Additionally, I will rename the 'county_fips' variable to 'fips' for consistency.

In [151]:
d18.rename({'diagnosed diabetes percentage' : 'pct_diabetes18', 'county_fips': 'fips'}, axis = 1, inplace = True) #renames columns

d18.columns #shows revised list of columns

Index(['fips', 'county', 'state', 'pct_diabetes18'], dtype='object')

Now, I will assess for null values.

In [152]:
d18.isnull().sum() #shows number of missing values for each column

fips              1
county            1
state             1
pct_diabetes18    1
dtype: int64

There is exactly 1 null value in each row. My thought is that this may be an empty row.

I will assess below.

In [153]:
d18.loc[d18['county'].isnull()] #shows the row missing the value in the county column

fips county state  pct_diabetes18
3141   NaN    NaN   NaN             NaN

Yes, this row is empty. It is likely the row that contained the download information ('US Diabetes Surveillance System...') in the year column.

This blank row will be removed.

In [154]:
d18.shape #shows the layout of the dataframe

(3142, 4)

In [155]:
d18 = d18.dropna() #drops empty row

d18.shape #shows revised layout

(3141, 4)

I notice that this dataframe contains 3141 rows, whereas the Health dataframe contained 3143.

I will attempt to determine the reason for this below.

In [156]:
d18.tail() #shows bottom 5 rows of dataframe

fips             county    state  pct_diabetes18
3136  56037.0  Sweetwater County  Wyoming             7.8
3137  56039.0       Teton County  Wyoming             3.8
3138  56041.0       Uinta County  Wyoming             8.4
3139  56043.0    Washakie County  Wyoming             7.4
3140  56045.0      Weston County  Wyoming             7.6

In [157]:
health.tail() #shows bottom 5 rows of health dataframe

fips state      county  pct_diabetes_adults08  pct_diabetes_adults13  \
3138  56037    WY  Sweetwater                    6.8                    8.1   
3139  56039    WY       Teton                    4.1                    4.8   
3140  56041    WY       Uinta                    6.3                    9.0   
3141  56043    WY    Washakie                   10.5                   12.0   
3142  56045    WY      Weston                    7.1                   10.0   

      pct_obese_adults12  pct_obese_adults17  pct_hspa17  recfac11  recfac16  \
3138                24.6                28.8         NaN         4         6   
3139                24.6                28.8         NaN         9        13   
3140                24.6                28.8         NaN         3         2   
3141                24.6                28.8         NaN         1         1   
3142                24.6                28.8         NaN         1         0   

      pch_recfac_11_16  recfacpth11  recfacpth16  pch_recfacpth_11_16  
3138         50.000000     0.090882     0.135609            49.213470  
3139         44.444444     0.419072     0.560828            33.826095  
3140        -33.333333     0.143548     0.096567           -32.728180  
3141          0.000000     0.118203     0.122130             3.321935  
3142       -100.000000     0.140036     0.000000          -100.000000

In [158]:
d18.fips.describe() #shows min, max, and other values in county fips (d18)

count     3141.000000
mean     30382.167144
std      15164.694955
min       1001.000000
25%      18177.000000
50%      29175.000000
75%      45081.000000
max      56045.000000
Name: fips, dtype: float64

In [159]:
health.fips.describe() #shows min, max, and other values in county fips (health)

count     3143.000000
mean     30390.411709
std      15164.717720
min       1001.000000
25%      18178.000000
50%      29177.000000
75%      45082.000000
max      56045.000000
Name: fips, dtype: float64

The two datasets have the same minimum and maximum fips score, but slightly different count and other information.

There may be two rows missing from the diabetes 2018 dataset. I will attempt to determine if this is the case.

In [160]:
d18.county.nunique() #show the number of unique values in the county column (d18)

1876

In [161]:
health.county.nunique() #shows the number of unique values in the county column (health)

1832

In [162]:
d18.state.unique() #displays the states (d18)

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [163]:
health.state.unique() #displays the states (health)

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
       'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY',
       'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], dtype=object)

It appears that there are 1876 unique county names in the Diabetes 2018 atlas, and only 1832 in the health dataset. However, both contain the same states. Per earlier analysis, neither dataset is missing values in the county column.

I can look for matching or non-matching values in SQL if the counties have the same name. 

This will require removing " County" from the county names in the d18 set.

In [164]:
d18.head(2) #shows top 2 rows of dataframe

fips          county    state  pct_diabetes18
0  1001.0  Autauga County  Alabama             9.5
1  1003.0  Baldwin County  Alabama             8.4

In [165]:
d18['county'] = d18['county'].str.replace(" County" , "") #removes the space + County from values

d18.head(2) #shows top 2 rows of revised dataframe

fips   county    state  pct_diabetes18
0  1001.0  Autauga  Alabama             9.5
1  1003.0  Baldwin  Alabama             8.4

The county names have been revised. 

The states in this dataset are not abbreviated, whereas the ones in the health dataset are. Additionally, the columns are ordered differently between the two datasets...

In order to save time and effort, the state names and column order will not be revised, as I will be searching/comparing unique county names using SQL. 

I will enter the d18 fips codes into SQL as type integer so that they will match with those in the Food Environment Atlas.

Before saving the cleaned dataframe as a csv, I will observe the percent diabetes values for any issues.

In [166]:
d18.fips = d18['fips'].astype(int) #s

d18.fips.dtype

dtype('int64')

In [167]:
d18.pct_diabetes18.describe() #shows a statistical summary for the % diabetes value

count    3141.000000
mean        8.724292
std         1.794746
min         3.800000
25%         7.400000
50%         8.400000
75%         9.700000
max        17.900000
Name: pct_diabetes18, dtype: float64

No issues are apparent in this column.

The cleaned dataframe will be saved as a csv file.

In [168]:
d18.to_csv('../data/DiabetesAtlasData_CLEAN.csv', index = False) #saves clean dataframe to a new csv

## Additional Data - Mental Health Providers

This dataset contains state-level information regarding mental health (rankings, and the number of mental health providers per 100,000 population.)

If there are no issues, I will add this information into the Health dataset for use in modeling.

In [169]:
file_path = '../data/state_mh_providers.csv'

mhp = pd.read_csv(file_path)

In [170]:
mhp.head()

state rank18  per100th18 rank17  per100th17
0     Alabama     50        92.6     50        85.0
1      Alaska      7       391.2      8       364.2
2     Arizona     47       129.3     47       121.9
3    Arkansas     27       226.0     26       213.3
4  California     11       338.0     10       315.5

In [171]:
mhp.shape

(51, 5)

In [172]:
mhp.isnull().sum()

state         0
rank18        0
per100th18    0
rank17        0
per100th17    0
dtype: int64

There are the number of expected states, and no null values.

In [173]:
mhp.dtypes

state          object
rank18         object
per100th18    float64
rank17         object
per100th17    float64
dtype: object

The state column should be an object, however the rank columns should be integers. I will look more closely.

In [174]:
mhp.rank17.unique()

array(['50', '8', '47', '26', '10', '11', '9', '19', '•', '41', '46',
       '22', '29', '28', '42', '44', '34', '27', '18', '3', '23', '1',
       '20', '25', '45', '36', '16', '21', '30', '15', '31', '7', '17',
       '24', '37', '32', '5', '2', '33', '6', '39', '38', '43', '49',
       '14', '4', '40', '13', '48', '35', '12'], dtype=object)

In [175]:
mhp.rank18.unique()

array(['50', '7', '47', '27', '11', '10', '9', '20', '•', '41', '46',
       '22', '32', '28', '42', '43', '35', '29', '18', '3', '24', '1',
       '19', '23', '44', '36', '16', '21', '31', '15', '30', '8', '17',
       '25', '37', '26', '6', '2', '33', '5', '39', '38', '45', '49',
       '14', '4', '40', '12', '48', '34', '13'], dtype=object)

There is a dot value in the rank columns. By observation of the tables online, I do recall that this was used as a placeholder for the District of Columbia, which was not assigned a rank.

I will need to assign it one, as I do plan to use the rank columns to see if they are predictive of diabetes.

During the first phase of EDA, in which I will use SQL, I will order the per100th columns to see where DC fits in, and adjust the ranks accordingly. 

In [176]:
mhp.describe()

per100th18  per100th17
count   51.000000   51.000000
mean   257.519608  240.937255
std    112.301669  106.857724
min     92.600000   85.000000
25%    174.550000  163.800000
50%    233.700000  216.800000
75%    332.350000  309.350000
max    590.900000  547.300000

I see no additional issues. No changes were made, and I will leave the csv as-is.

## Additional Data - Received Mental Health Services in the Past Year- by Age Group & State

As I described the README, I found this information in a table, which I then transferred into a spreadsheet and downloaded as a CSV. Before creating the CSV, however, I completed some of the cleaning in google sheets for ease of processing. (The original information is present and able to be viewed as a csv in the data folder if needed.)

First, I removed the Cl upper/lower limit columns. I renamed the remaining columns for ease of use. Next, I removed the "total U.S." row, along with the regional rows (northeast, midwest, e.t.c.) so that only the states remain. I then removed the "order" column, which was the index. Afterward, I changed the format to "number."

All that should need to be done here is to multiply the numerical columns by 100 in order to match the scale of the  percent values in the Food Environment Atlas.

In [177]:
file_path = '../data/NSDUH_RcvdMHServes2016.csv'

mhs = pd.read_csv(file_path)

In [178]:
mhs.head() #shows top 5 rows of dataframe

state  18plus  18_25  26plus
0     Alabama    0.13   0.11    0.13
1      Alaska    0.14   0.13    0.14
2     Arizona    0.12   0.10    0.12
3    Arkansas    0.16   0.13    0.16
4  California    0.12   0.10    0.12

In [179]:
mhs.shape #shows layout of the dataframe

(51, 4)

In [180]:
mhs.isnull().sum() #shows number of missing values per column

state     0
18plus    0
18_25     0
26plus    0
dtype: int64

I will now remove multiply the numerical columns by 100 so that they match the Food Environment Atlas percentages.

In [181]:
mhs['18plus'] = mhs['18plus'] * 100

mhs['18_25'] = mhs['18_25'] * 100

mhs['26plus'] = mhs['26plus'] * 100

mhs.head()

state  18plus  18_25  26plus
0     Alabama    13.0   11.0    13.0
1      Alaska    14.0   13.0    14.0
2     Arizona    12.0   10.0    12.0
3    Arkansas    16.0   13.0    16.0
4  California    12.0   10.0    12.0

In [182]:
mhs.dtypes

state      object
18plus    float64
18_25     float64
26plus    float64
dtype: object

I am remembering now that I cannot enter column names that begin with a number into SQL. I will need to edit the names of the numerical columns.

In [183]:
mhs.rename({'18plus': 'age18plus', '18_25': 'age18_25', '26plus': 'age26plus'}, axis=1, inplace = True)

mhs.columns

Index(['state', 'age18plus', 'age18_25', 'age26plus'], dtype='object')

The data cleaning is complete. I will save this into a new csv.

In [184]:
mhs.to_csv('../data/NSDUH_RcvdMHServes2016_CLEAN.csv', index=False)

## Discussion

As mentioned in the Food Environmental Atlas README, there are more than 280 variables in the original dataset. I removed a number of these during preliminary analysis and cleaning. I anticipate that I will remove more before modeling begins. 

Additionally, I did not observe any -9999 values, but there are missing values in some of the columns. Before I decide on what to impute or remove, I will perform additional EDA. This will be performed beginning in the next notebook, using SQL.